#GCC PATH
GCC_DIR =

#COMPILER
CC = $(GCC_DIR)gcc
CXX = $(GCC_DIR)g++
AR = $(GCC_DIR)ar

WiBench_INSTALL_DIR :=/home/yajchen/Documents/WiBench/git_WiB/pubWiB/wibench
ifeq "$(WiBench_INSTALL_DIR)" ""
$(error WiBench Install directory is not defined)
endif

KERNEL_DIR := $(WiBench_INSTALL_DIR)/src/kernel
APP_DIR := $(WiBench_INSTALL_DIR)/src/app
UTIL_DIR := $(WiBench_INSTALL_DIR)/src/util
CHANNEL_DIR := $(WiBench_INSTALL_DIR)/src/channel
HARQ_DIR := $(WiBench_INSTALL_DIR)/src/harq

KERNEL_BUILD_DIR := $(WiBench_INSTALL_DIR)/build/kernel 
APP_BUILD_DIR := $(WiBench_INSTALL_DIR)/build/app

INC_FLAGS = -I$(WiBench_INSTALL_DIR)/src/include

CC_DEBUG_FLAGS=
CXX_DEBUG_FLAGS = 

CC_OPT_FLAGS =
CXX_OPT_FLAGS = -O3

CCFLAGS += $(CC_DEBUG_FLAGS)
CCFLAGS += $(CC_OPT_FLAGS)
CCFLAGS += $(INC_FLAGS)

CXXFLAGS += $(CXX_DEBUG_FLAGS)
CXXFLAGS += $(CXX_OPT_FLAGS)
CXXFLAGS += $(INC_FLAGS)
